### ISSUE TITLE
EncodingForModel: no encoding for model gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by ethanchancc18** [pkoukk/tiktoken-go#12]
```golang
tkm, err := tiktoken.EncodingForModel(Model)
	if err != nil {
		fmt.Println(fmt.Errorf("EncodingForModel: %v", err))
		return
	}
```
我在执行这个model gpt-3.5-turbo-0301 报错找不到encoding ，我看了源码MODEL_TO_ENCODING没有这个模型

**Comment by pkoukk** [comment]
衍生模型的支持之前没发tag支持，在终端执行
`go get -d github.com/pkoukk/tiktoken-go`或者`go get -d github.com/pkoukk/tiktoken-go@v0.1.1`
相关支持代码在`MODEL_PREFIX_TO_ENCODING`定义中
