### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by igoose1** [pkoukk/tiktoken-go#2]
Hi, pkoukk!

Nice port! However, I noticed that there is no explicit license note in the repository, which means the code cannot be used by others and is considered proprietary.

If you would like to publish the code as a Free and Open Source Software, I recommend choosing a license from https://www.gnu.org/licenses/license-list.html.

Thank you for publishing this code and I hope you find my suggestion helpful.

**Comment by pkoukk** [comment]
I appreciate your advice. Just to let you know, I have added a MIT LICENSE now. Thanks again for your help!
