### ISSUE TITLE
not support for gpt-3.5-turbo-16k-0613

### ISSUE THREAD

**Issue by mengmengmengqiang** [pkoukk/tiktoken-go#28]
tkm, err := tiktoken.EncodingForModel("gpt-3.5-turbo-16k-0613")

get err even loaded file from https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken

**Comment by pkoukk** [comment]
It works fine for me. 
Try run `go get -u github.com/pkoukk/tiktoken-go` to update your dependencies.
If there are still errors, please provide me with more details about the errors.

**Comment by zachsmith1** [comment]
This should satisfy the issue you are seeing: https://github.com/pkoukk/tiktoken-go/pull/32
