### ISSUE TITLE
help for count token 

### ISSUE THREAD

**Issue by 137-rick** [pkoukk/tiktoken-go#3]
hi sir 
this is very good tools! useful
can you support an token counter?
or any suggestion how can i do this?

ref: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
chapter: 6. Counting tokens for chat API calls

**Comment by aphilas** [comment]
```go
func countTokens(prompt string) (int, error) {
	enc, err := tiktoken.GetEncoding(tokenizerEncoding)
	if err != nil {
		return 0, err
	}

	tokens := enc.Encode(prompt, nil, nil)

	return len(tokens), nil
}
```

Transliteration of 
```py
def num_tokens_from_string(string: str, encoding_name: str) -> int:
    """Returns the number of tokens in a text string."""
    encoding = tiktoken.get_encoding(encoding_name)
    num_tokens = len(encoding.encode(string))
    return num_tokens
```

from the link you shared [^1]. 

Did I miss something?

[^1]: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb?rgh-link-date=2023-03-30T09%3A05%3A53Z
