### ISSUE TITLE
Can a Tiktoken instance be shared by multiple go routines?

### ISSUE THREAD

**Issue by WqyJh** [pkoukk/tiktoken-go#33]
It seems the `GetEncoding` is not cheap to call since it have to compile regex. Creating a `Tiktoken` instance before every token calculation is not efficient. Therefore, if `Tiktoken` instance can be shared by multiple go routines, then we only need to create it once, which is more efficient.

**Comment by qhenkart** [comment]
@WqyJh I would assume not. There are a lot of maps being passed around and modified under the hood

**Comment by pkoukk** [comment]
Yes. All `Tiktoken` methods are thread-safe to call, you can safely use them concurrently in Go routines.

**Comment by lwabish** [comment]
I am wrapping tiktoken into a http server to offer an api(something like /tokenize) and found some performance issue when input get larger (like 64k or above): 
With 1 concurrency , avg request duration is 109.5ms. 
With 10 concurrency, avg request duration goes up to 209.09ms.

The server and my loadtest client are both running in my local mac thus no computing resource should be a bottleneck, I think.
